Release version 0.5.0

diff --git a/dist/contr b/dist/contr
--- a/dist/contr
+++ b/dist/contr
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
 # SPDX-License-Identifier: Unlicense
-VERSION='0.4.0'
+VERSION='0.5.0'
 CMD="$(basename "$0")"
 PWD=$(pwd)
 USER_ID=$(id -u)
@@ -47,9 +47,9 @@ Environment variables:
 
 Examples:
   $CMD alpine
-  $CMD -n node:alpine sh
   $CMD --make-config=amazon/aws-cli
   $CMD -n amazon/aws-cli aws --version
+  $CMD -n -p 3000 node:alpine npm run dev -- --host 0.0.0.0
 EOF
     exit
 }
@@ -282,7 +282,7 @@ EOF_OPTIONS_FILE
 # profile - contr
 # User-specific environment for containers
 #
-# This file is sourced (. command) by the entrypoint shell-script inside the
+# This file is sourced (. command) by the shell's profile/rc file inside the
 # container. Use it to do any complex initialization you may require for a
 # container, that can't be done with the simpler environment file.
 #
@@ -448,13 +448,83 @@ set_cwd_mode() {
     log_debug "set_cwd_mode() cwd_mode=$cwd_mode"
 }
 
+# Add 127.0.0.1 as bind address to published ports unless an address is explicitly set
+# For ports 1024 and above, bind container ports to the same port number on the host if not specified
+make_publish_local_only() {
+    opt_arg="${1#'--publish='}"
+    opt_arg="${opt_arg#'-p='}"
+    opt_flag= && [ "$opt_arg" != "$1" ] && opt_flag='--publish='
+
+    print_arg() {
+        if [ "$2" -ge "${ip_unprivileged_port_start:-0}" ]; then
+            printf '%s%s:%s:%s' "$opt_flag" "$1" "${3:-"$2"}" "$2"
+        else
+            printf '%s%s:%s:%s' "$opt_flag" "$1" "${3:-}" "$2"
+        fi
+    }
+    case "$1" in
+        *.*.*.*::*) # arg is an IP address and a container port
+            container_port="${opt_arg##*:}"
+            ip_address="${opt_arg%%::*}"
+            print_arg "$ip_address" "$container_port"
+            ;;
+        *.*.*.*:*:*) printf '%s' "$1" ;; # arg is an IP address and a pair of host:container ports, ignore
+        *:*)                             # arg is a pair of host:container ports
+            container_port="${opt_arg##*:}"
+            host_port="${opt_arg%%:*}"
+            print_arg '127.0.0.1' "$container_port" "$host_port"
+            ;;
+        *) print_arg '127.0.0.1' "$opt_arg" ;; # If there are no colons, arg is only a container port number
+    esac
+}
+
+# Add noexec option to a volume definition unless an exec mode is explicitly set
+make_volume_noexec() {
+    case "$1" in
+        *:*)
+            volume_opts="${1##*:}"
+            case "$volume_opts" in
+                */*) printf '%s' "${1}:noexec" ;; # Slashes mean the last component is a path, there are no options
+                *exec*) printf '%s' "$1" ;;       # exec/noexec already present, don't change anything
+                *) printf '%s' "${1},noexec" ;;   # Add noexec to options list
+            esac
+            ;;
+        *)
+            # If there are no colons we do nothing as this is an anonymous volume, which
+            # does not accept options, and in our case (podman-run --rm) is transient anyway
+            printf '%s' "$1"
+            ;;
+    esac
+}
+
+initialize_run_variables() {
+    user_home="$HOME"
+    volume_home=1
+    cwd_mode='rw,exec'
+
+    is_tty=
+    CONTR_PS1=
+    if [ -t 0 ]; then
+        is_tty=1
+        xterm_title=$(printf '\001\033]2;\w — contr ⬢ %s\a\002' "$image")
+        CONTR_PS1="$(printf '%s\n\001\033[1;36m\002\w\001\033[m\002 inside \001\033[1;35m\002⬢ %s\001\033[m\002\n\001\033[1;90m\002❯\001\033[m\002 ' "$xterm_title" "$image")"
+    fi
+
+    ip_unprivileged_port_start=1024
+    if [ "$USER_ID" = 0 ]; then
+        # if running as root, ignore 'ip_unprivileged_port_start'
+        ip_unprivileged_port_start=
+    elif command -v sysctl >/dev/null; then
+        ip_unprivileged_port_start="$(sysctl net.ipv4.ip_unprivileged_port_start)" # net.ipv4.ip_unprivileged_port_start = 1024
+        ip_unprivileged_port_start="${ip_unprivileged_port_start##*[!0-9]}"
+    fi
+    log_debug "initialize_run_variables() ip_unprivileged_port_start=$ip_unprivileged_port_start"
+}
+
 main() {
     read_arguments "$@"
     check_dependencies cat grep mkdir tr
     set_config_files
-    user_home="$HOME"
-    volume_home=1
-    cwd_mode='rw,exec'
 
     if [ "$action" = 'make-config' ]; then
         write_config_files "$config_dir"
@@ -466,6 +536,7 @@ main() {
 
     # From here on we assume the default action = 'podman-run'
     check_dependencies cat chmod grep mkdir podman tr
+    initialize_run_variables
 
     # Read options from command line
     while :; do
@@ -540,26 +611,7 @@ main() {
         log_debug "main() \$*=$*"
     fi
 
-    # Add noexec option to a volume definition unless an exec mode is explicitly set
-    make_volume_noexec() {
-        case "$1" in
-            *:*) ;;
-            *)
-                # If there are no colons we do nothing as this is an anonymous volume, which
-                # does not accept options, and in our case (podman-run --rm) is transient anyway
-                printf '%s' "$1"
-                exit
-                ;;
-        esac
-        volume_opts="${1##*:}"
-        case "$volume_opts" in
-            */*) printf '%s' "${1}:noexec" ;; # Slashes mean the last component is a path, there are no options
-            *exec*) printf '%s' "$1" ;;       # exec/noexec already present, don't change anything
-            *) printf '%s' "${1},noexec" ;;   # Add noexec to options list
-        esac
-    }
-
-    # Change all volume arguments to include option noexec by default, unless exec is explicitly set
+    # Change Podman options arguments to override Podman's defaults with ours
     log_debug "main() image_arg_pos=$image_arg_pos"
     argc="$#"
     i=1
@@ -570,7 +622,18 @@ main() {
         if [ "$i" -lt "$image_arg_pos" ]; then
             log_debug "${i}: $opt"
             case "$opt" in
-                --volume=*)
+                -p=* | --publish=*)
+                    opt=$(make_publish_local_only "$opt")
+                    log_debug "${i}: $opt"
+                    ;;
+                -p | --publish)
+                    shifts=2
+                    opt_arg=$(make_publish_local_only "$2")
+                    opt_arg_pos=$((i + 1))
+                    log_debug "${opt_arg_pos}: $2"
+                    log_debug "${opt_arg_pos}: $opt_arg"
+                    ;;
+                -v=* | --volume=*)
                     opt=$(make_volume_noexec "$opt")
                     log_debug "${i}: $opt"
                     ;;
@@ -588,22 +651,16 @@ main() {
         i=$((i + shifts))
     done
     log_debug "main() \$*=$*"
-    [ "$argc" = "$#" ] || abort "Error processing volume arguments. We should to have $argc arguments but got $# instead"
+    [ "$argc" = "$#" ] || abort "Error processing arguments. We should have $argc arguments but got $# instead"
 
     [ "$entrypoint_file" ] && write_entrypoint_file "$entrypoint_file"
-    is_tty=
-    CONTR_PS1=
-    if [ -t 0 ]; then
-        is_tty=1
-        xterm_title=$(printf '\001\033]2;\w — contr ⬢ %s\a\002' "$image")
-        CONTR_PS1="$(printf '%s\n\001\033[1;36m\002\w\001\033[m\002 inside \001\033[1;35m\002⬢ %s\001\033[m\002\n\001\033[1;90m\002❯\001\033[m\002 ' "$xterm_title" "$image")"
-    fi
 
     exec podman run -i ${is_tty:+-t} --rm \
         --tz=local \
         --security-opt=label=disable \
         --group-add=keep-groups \
         --user="0:0" \
+        --pull=newer \
         --env=CONTR_DEBUG \
         ${volume_home:+"--volume=$HOME"} \
         ${cwd_mode:+"--volume=${PWD}:${PWD}:$cwd_mode" "--workdir=$PWD"} \
