Release version 0.7.0

diff --git a/dist/contr b/dist/contr
--- a/dist/contr
+++ b/dist/contr
@@ -1,6 +1,6 @@
-#!/usr/bin/env sh
+#!/bin/sh
 # SPDX-License-Identifier: Unlicense
-VERSION='0.6.0'
+VERSION='0.7.0'
 CMD="$(basename "$0")"
 PWD=$(pwd)
 USER_ID=$(id -u)
@@ -31,6 +31,8 @@ Options:
   -6                       Mount the current working directory with read and write permissions '--cwd-mode=rw'
   -7                       Mount the current working directory with read, write and execute permissions (default) '--cwd-mode=rw,exec'
   -n                       Allow network access
+  --no-persist             Override "page.codeberg.contr.persist" label from image, canceling its mount points
+  --persist=PATH[:exec]    Create a mount point at PATH to persist its data across invocations. PATH must be absolute or relative to [~ | home]
   --pio                    Per-Image Override: per-image config files override instead of adding to global config files. Useful when the per-image config conflicts with the global config
   --plain                  Do not override the image's entrypoint script
   --pure                   Ignore all configuration files and custom entrypoint
@@ -63,6 +65,26 @@ abort() {
 }
 missing_opt_arg() { abort "Missing argument for option $*. Run $CMD --help"; }
 
+# substitute_characters text pattern [replacement]
+# Substitute every instance of the pattern characters in text with replacement string
+# This function uses only shell builtins and has no external dependencies (f.e. on sed)
+# This is slower than using sed on large inputs, but faster on many invocations with small inputs
+substitute_characters() {
+	case $- in *f*) NS__outer_noglob='-f' ;; *) NS__outer_noglob='+f' ;; esac
+	NS__outer_ifs=$IFS
+	set -f # Disable Pathname Expansion (aka globbing)
+	IFS=$2
+	unset -v NS__last_field
+	for NS__field in ${1}P; do
+		printf '%s' ${NS__last_field+"${NS__last_field}${3}"}
+		NS__last_field=$NS__field
+	done
+	printf '%s' "${NS__last_field%?}"
+	IFS=$NS__outer_ifs
+	set "$NS__outer_noglob"
+	unset -v NS__outer_noglob NS__outer_ifs NS__last_field NS__field
+}
+
 # Remove tag from a container image's name/URI
 remove_tag() {
 	case "${1##*:}" in          # Get the last component
@@ -73,7 +95,13 @@ remove_tag() {
 
 # Sanitize string for use in filename. Replaces / and : with _
 sanitize_for_fs() {
-	printf '%s' "$*" | tr '/:' '_'
+	substitute_characters "$1" '/:' '_'
+}
+
+# get_label IMAGE LABEL
+# Print the value of a Label from a container image
+get_label() {
+	podman image inspect --format "{{index .Config.Labels \"${2}\"}}" "$1"
 }
 
 read_arguments() {
@@ -142,8 +170,9 @@ read_arguments() {
 		[ "$image" ] || abort "An image must be provided. Run $CMD --help"
 	fi
 
-	image_name="$(remove_tag "$image")"
-	log_debug "read_arguments() image='$image' image_name='$image_name'"
+	image_uri="$(remove_tag "$image")"
+	image_name=${image_uri##*/}
+	log_debug "read_arguments() image='${image}' image_uri='${image_uri}' image_name='${image_name}'"
 }
 
 check_dependencies() {
@@ -338,7 +367,7 @@ EOF_PROFILE_FILE
 write_entrypoint_file() {
 	print_entrypoint_file() {
 		cat <<"EOF_ENTRYPOINT_FILE"
-#!/usr/bin/env sh
+#!/bin/sh
 # SPDX-License-Identifier: Unlicense
 # entrypoint - contr
 #
@@ -497,10 +526,79 @@ make_volume_noexec() {
 	esac
 }
 
+get_persistence_volume_specifier_() {
+	mount_specifier_=$1
+	case "$mount_specifier_" in "~" | "~"[/:]*) mount_specifier_="home${mount_specifier_#"~"}" ;; esac
+	case "$mount_specifier_" in
+	*:ro | *:ro,exec | *:ro,noexec | *:exec,ro | *:noexec,ro) return 4 ;;
+	*:exec | *:noexec | *:rw,exec | *:rw,noexec | *:exec,rw | *:noexec,rw) ;;
+	*:r[ow]) mount_specifier_="${mount_specifier_},noexec" ;;
+	*) mount_specifier_="${mount_specifier_}:noexec" ;;
+	esac
+	case "$mount_specifier_" in home | home[/:]*) volume_home= ;; esac
+	mount_point_=$mount_specifier_
+	case "$mount_point_" in
+	home | home[/:]*) mount_point_="${HOME}${mount_point_#home}" ;;
+	/*) ;;
+	*) return 3 ;;
+	esac
+	volume_name_=$(substitute_characters "${mount_specifier_%:*}" '/' '__')
+	volume_name_="contr-persist.$(sanitize_for_fs "$image_name").$(sanitize_for_fs "$volume_name_")"
+	volume_specifier="${volume_name_}:${mount_point_}"
+}
+
+create_persistence_volumes() {
+	persist_label=$(get_label "$image" page.codeberg.contr.persist)
+	outer_ifs=$IFS
+	IFS='	'
+	for mount_specifier in $persist_label; do
+		IFS=$outer_ifs
+		get_persistence_volume_specifier_ "$mount_specifier" && :
+		status=$?
+		if [ "$status" -eq 3 ]; then
+			abort "Error in image's 'page.codeberg.contr.persist' label. Persistent mounts must be absolute paths, or relative to [~ | home]. Incorrect path is '${mount_specifier}'"
+		elif [ "$status" -eq 4 ]; then
+			abort "Error in image's 'page.codeberg.contr.persist' label. Persistent mounts can not be read-only. Incorrect path is '${mount_specifier}'"
+		elif [ "$status" -gt 0 ]; then
+			abort "Unknown error in image's 'page.codeberg.contr.persist' label. Incorrect path is '${mount_specifier}'"
+		fi
+		image_persistence_volumes="${image_persistence_volumes}--volume=${volume_specifier}
+"
+	done
+	log_debug "[create_persistence_volumes] image_persistence_volumes=[${image_persistence_volumes}]"
+}
+
+add_cli_persistence_volume() {
+	mount_specifier=$1
+	get_persistence_volume_specifier_ "$mount_specifier" && :
+	status=$?
+	if [ "$status" -eq 3 ]; then
+		abort "Error in --persist=${mount_specifier} option. Persistent mounts must be absolute paths, or relative to [~ | home]"
+	elif [ "$status" -eq 4 ]; then
+		abort "Error in --persist=${mount_specifier} option. Persistent mounts can not be read-only"
+	elif [ "$status" -gt 0 ]; then
+		abort "Unknown error in --persist=${mount_specifier} option"
+	fi
+	cli_persistence_volumes="${cli_persistence_volumes}--volume=${volume_specifier}
+"
+}
+
+pull_image_if_missing() {
+	podman image exists "$image" && :
+	status=$?
+	if [ "$status" -eq 125 ]; then
+		abort "Podman error trying to access local image storage. podman-image-exists returned code 125"
+	elif [ "$status" -ne 0 ]; then
+		podman image pull "$image" || abort "Image '${image}' does not exist and Podman failed to pull a new image"
+	fi
+}
+
 initialize_run_variables() {
 	user_home="$HOME"
 	volume_home=1
 	cwd_mode='rw,exec'
+	image_persistence_volumes=
+	cli_persistence_volumes=
 
 	is_tty=
 	CONTR_PS1=
@@ -523,7 +621,7 @@ initialize_run_variables() {
 
 main() {
 	read_arguments "$@"
-	check_dependencies cat grep mkdir tr
+	check_dependencies cat grep mkdir
 	set_config_files
 
 	if [ "$action" = 'make-config' ]; then
@@ -535,8 +633,10 @@ main() {
 	fi
 
 	# From here on we assume the default action = 'podman-run'
-	check_dependencies cat chmod grep mkdir podman tr
+	check_dependencies cat chmod grep mkdir podman
 	initialize_run_variables
+	pull_image_if_missing
+	create_persistence_volumes
 
 	# Read options from command line
 	while :; do
@@ -546,6 +646,11 @@ main() {
 		--cwd-mode | --cwd-mode=) missing_opt_arg "$1" ;;
 		--cwd-mode=*)
 			set_cwd_mode "${1#'--cwd-mode='}"
+			;;
+		--no-persist) image_persistence_volumes= ;;
+		--persist | --persist=) missing_opt_arg "$1" ;;
+		--persist=*)
+			add_cli_persistence_volume "${1#'--persist='}"
 			;;
 		-[04567] | -n[04567] | -[04567]n)
 			opt="${1%n}"
@@ -580,6 +685,7 @@ main() {
 		image_arg_pos=$((image_arg_pos - 1)) # Decrement image position in arguments list
 	done
 	log_debug "main() \$*=$*"
+	log_debug "[add_cli_persistence_volume] cli_persistence_volumes=[${cli_persistence_volumes}]"
 	[ ! "$cwd_mode" ] && [ ! "$user_home" ] && volume_home=
 	[ "$cwd_mode" ] && [ "$HOME" = "$PWD" ] && abort "Do not use contr in the home directory. This is not supported, and would expose your entire home directory inside the container, defeating the security purpose of this program."
 
@@ -655,12 +761,13 @@ main() {
 
 	[ "$entrypoint_file" ] && write_entrypoint_file "$entrypoint_file"
 
+	# shellcheck disable=SC2086
 	exec podman run -i ${is_tty:+-t} --rm \
 		--tz=local \
 		--security-opt=label=disable \
 		--group-add=keep-groups \
 		--user="0:0" \
-		--pull=newer \
+		--pull=never \
 		--env=CONTR_DEBUG \
 		${volume_home:+"--volume=$HOME"} \
 		${cwd_mode:+"--volume=${PWD}:${PWD}:$cwd_mode" "--workdir=$PWD"} \
@@ -676,6 +783,8 @@ main() {
 		${profile_file:+"--env=CONTR_PROFILE_1=/run/contr/profile1"} \
 		${per_image_profile_file:+"--volume=${per_image_profile_file}:/run/contr/profile2:ro,noexec"} \
 		${per_image_profile_file:+"--env=CONTR_PROFILE_2=/run/contr/profile2"} \
+		${image_persistence_volumes} \
+		${cli_persistence_volumes} \
 		"$@"
 }
 
